name: Action

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Build Docs
        run: cd docs && pnpm build
        
      - name: Setup
        run: pnpm install netlify-cli -g
        
      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.8.2
        with:
           # Auth token to use with netlify
           NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN }}
           # Your Netlify site id
           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
           # Should the site be deployed to production?
           NETLIFY_DEPLOY_TO_PROD: true
           # Directory where built files are stored
           build_directory: "docs/src/.island/dist"
